In [5]:
import numpy as np

x = [1, 2, 3, 4]
y = np.exp(x)
s = sum(y)
print(y/s)

[0.0320586  0.08714432 0.23688282 0.64391426]


In [15]:
a1 = np.array([[1, 2, 3, 4], [9, 10, 11, 12]])
a2 = np.array([[5, 6, 7, 8]])

np.concatenate((a1, a2), axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [16]:
for k in reversed([1, 2, 3,4]):
    print(k)

4
3
2
1


In [21]:
a = np.array([[1, 0, 0, 1], 
              [0, 1, 1, 0]])

b = np.array([[1, 0, 0, 0], 
              [0, 1, 0, 1]])

cost = np.sum((a - b)**2, axis=0)
print(a[0])

[1 0 0 1]


In [31]:
print(a[:, 1].T)

[0 1]


In [24]:
b[0, :]

array([1, 0, 0, 0])

In [40]:
c = np.array([[1,2], [3, 4]])
d = np.array([[1, 2],[3, 4]])
print(c*d)
print(c.shape)
print(d.shape)

[[ 1  4]
 [ 9 16]]
(2, 2)
(2, 2)


In [42]:
np.argmax(np.array([[0.9, 0.6, 0.3], [0.1, 0.4, 0.7]]), axis=0)

array([0, 0, 1])

In [1]:
for L in range(2, 0, -1):
    print(L)

2
1


In [2]:
import numpy as np
print(np.cos(0))

1.0
